export interface Country {
  name: string;
  code: string;
  iso: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: "Malaysia", code: "+60", iso: "MY", flag: "https://flagcdn.com/w40/my.png" },
  { name: "Singapore", code: "+65", iso: "SG", flag: "https://flagcdn.com/w40/sg.png" },
  { name: "Indonesia", code: "+62", iso: "ID", flag: "https://flagcdn.com/w40/id.png" },
  { name: "Thailand", code: "+66", iso: "TH", flag: "https://flagcdn.com/w40/th.png" },
  { name: "Timor-Leste", code: "+670", iso: "TL", flag: "https://flagcdn.com/w40/tl.png" },
  { name: "Vietnam", code: "+84", iso: "VN", flag: "https://flagcdn.com/w40/vn.png" },
  { name: "Philippines", code: "+63", iso: "PH", flag: "https://flagcdn.com/w40/ph.png" },
  { name: "Afghanistan", code: "+93", iso: "AF", flag: "https://flagcdn.com/w40/af.png" },
  { name: "Albania", code: "+355", iso: "AL", flag: "https://flagcdn.com/w40/al.png" },
  { name: "Algeria", code: "+213", iso: "DZ", flag: "https://flagcdn.com/w40/dz.png" },
  { name: "American Samoa", code: "+1", iso: "AS", flag: "https://flagcdn.com/w40/as.png" },
  { name: "Andorra", code: "+376", iso: "AD", flag: "https://flagcdn.com/w40/ad.png" },
  { name: "Angola", code: "+244", iso: "AO", flag: "https://flagcdn.com/w40/ao.png" },
  { name: "Anguilla", code: "+1", iso: "AI", flag: "https://flagcdn.com/w40/ai.png" },
  { name: "Antigua and Barbuda", code: "+1", iso: "AG", flag: "https://flagcdn.com/w40/ag.png" },
  { name: "Argentina", code: "+54", iso: "AR", flag: "https://flagcdn.com/w40/ar.png" },
  { name: "Armenia", code: "+374", iso: "AM", flag: "https://flagcdn.com/w40/am.png" },
  { name: "Aruba", code: "+297", iso: "AW", flag: "https://flagcdn.com/w40/aw.png" },
  { name: "Australia", code: "+61", iso: "AU", flag: "https://flagcdn.com/w40/au.png" },
  { name: "Austria", code: "+43", iso: "AT", flag: "https://flagcdn.com/w40/at.png" },
  { name: "Azerbaijan", code: "+994", iso: "AZ", flag: "https://flagcdn.com/w40/az.png" },
  { name: "Bahamas", code: "+1", iso: "BS", flag: "https://flagcdn.com/w40/bs.png" },
  { name: "Bahrain", code: "+973", iso: "BH", flag: "https://flagcdn.com/w40/bh.png" },
  { name: "Bangladesh", code: "+880", iso: "BD", flag: "https://flagcdn.com/w40/bd.png" },
  { name: "Barbados", code: "+1", iso: "BB", flag: "https://flagcdn.com/w40/bb.png" },
  { name: "Belarus", code: "+375", iso: "BY", flag: "https://flagcdn.com/w40/by.png" },
  { name: "Belgium", code: "+32", iso: "BE", flag: "https://flagcdn.com/w40/be.png" },
  { name: "Belize", code: "+501", iso: "BZ", flag: "https://flagcdn.com/w40/bz.png" },
  { name: "Benin", code: "+229", iso: "BJ", flag: "https://flagcdn.com/w40/bj.png" },
  { name: "Bermuda", code: "+1", iso: "BM", flag: "https://flagcdn.com/w40/bm.png" },
  { name: "Bhutan", code: "+975", iso: "BT", flag: "https://flagcdn.com/w40/bt.png" },
  { name: "Bolivia", code: "+591", iso: "BO", flag: "https://flagcdn.com/w40/bo.png" },
  { name: "Bosnia and Herzegovina", code: "+387", iso: "BA", flag: "https://flagcdn.com/w40/ba.png" },
  { name: "Botswana", code: "+267", iso: "BW", flag: "https://flagcdn.com/w40/bw.png" },
  { name: "Brazil", code: "+55", iso: "BR", flag: "https://flagcdn.com/w40/br.png" },
  { name: "British Indian Ocean Territory", code: "+246", iso: "IO", flag: "https://flagcdn.com/w40/io.png" },
  { name: "Brunei", code: "+673", iso: "BN", flag: "https://flagcdn.com/w40/bn.png" },
  { name: "Bulgaria", code: "+359", iso: "BG", flag: "https://flagcdn.com/w40/bg.png" },
  { name: "Burkina Faso", code: "+226", iso: "BF", flag: "https://flagcdn.com/w40/bf.png" },
  { name: "Burundi", code: "+257", iso: "BI", flag: "https://flagcdn.com/w40/bi.png" },
  { name: "Cambodia", code: "+855", iso: "KH", flag: "https://flagcdn.com/w40/kh.png" },
  { name: "Cameroon", code: "+237", iso: "CM", flag: "https://flagcdn.com/w40/cm.png" },
  { name: "Canada", code: "+1", iso: "CA", flag: "https://flagcdn.com/w40/ca.png" },
  { name: "Cape Verde", code: "+238", iso: "CV", flag: "https://flagcdn.com/w40/cv.png" },
  { name: "Cayman Islands", code: "+1", iso: "KY", flag: "https://flagcdn.com/w40/ky.png" },
  { name: "Central African Republic", code: "+236", iso: "CF", flag: "https://flagcdn.com/w40/cf.png" },
  { name: "Chad", code: "+235", iso: "TD", flag: "https://flagcdn.com/w40/td.png" },
  { name: "Chile", code: "+56", iso: "CL", flag: "https://flagcdn.com/w40/cl.png" },
  { name: "China", code: "+86", iso: "CN", flag: "https://flagcdn.com/w40/cn.png" },
  { name: "Colombia", code: "+57", iso: "CO", flag: "https://flagcdn.com/w40/co.png" },
  { name: "Comoros", code: "+269", iso: "KM", flag: "https://flagcdn.com/w40/km.png" },
  { name: "Congo", code: "+242", iso: "CG", flag: "https://flagcdn.com/w40/cg.png" },
  { name: "Cook Islands", code: "+682", iso: "CK", flag: "https://flagcdn.com/w40/ck.png" },
  { name: "Costa Rica", code: "+506", iso: "CR", flag: "https://flagcdn.com/w40/cr.png" },
  { name: "Croatia", code: "+385", iso: "HR", flag: "https://flagcdn.com/w40/hr.png" },
  { name: "Cuba", code: "+53", iso: "CU", flag: "https://flagcdn.com/w40/cu.png" },
  { name: "Cyprus", code: "+357", iso: "CY", flag: "https://flagcdn.com/w40/cy.png" },
  { name: "Czech Republic", code: "+420", iso: "CZ", flag: "https://flagcdn.com/w40/cz.png" },
  { name: "Denmark", code: "+45", iso: "DK", flag: "https://flagcdn.com/w40/dk.png" },
  { name: "Djibouti", code: "+253", iso: "DJ", flag: "https://flagcdn.com/w40/dj.png" },
  { name: "Dominica", code: "+1", iso: "DM", flag: "https://flagcdn.com/w40/dm.png" },
  { name: "Dominican Republic", code: "+1", iso: "DO", flag: "https://flagcdn.com/w40/do.png" },
  { name: "Ecuador", code: "+593", iso: "EC", flag: "https://flagcdn.com/w40/ec.png" },
  { name: "Egypt", code: "+20", iso: "EG", flag: "https://flagcdn.com/w40/eg.png" },
  { name: "El Salvador", code: "+503", iso: "SV", flag: "https://flagcdn.com/w40/sv.png" },
  { name: "Equatorial Guinea", code: "+240", iso: "GQ", flag: "https://flagcdn.com/w40/gq.png" },
  { name: "Eritrea", code: "+291", iso: "ER", flag: "https://flagcdn.com/w40/er.png" },
  { name: "Estonia", code: "+372", iso: "EE", flag: "https://flagcdn.com/w40/ee.png" },
  { name: "Ethiopia", code: "+251", iso: "ET", flag: "https://flagcdn.com/w40/et.png" },
  { name: "Faroe Islands", code: "+298", iso: "FO", flag: "https://flagcdn.com/w40/fo.png" },
  { name: "Fiji", code: "+679", iso: "FJ", flag: "https://flagcdn.com/w40/fj.png" },
  { name: "Finland", code: "+358", iso: "FI", flag: "https://flagcdn.com/w40/fi.png" },
  { name: "France", code: "+33", iso: "FR", flag: "https://flagcdn.com/w40/fr.png" },
  { name: "French Guiana", code: "+594", iso: "GF", flag: "https://flagcdn.com/w40/gf.png" },
  { name: "French Polynesia", code: "+689", iso: "PF", flag: "https://flagcdn.com/w40/pf.png" },
  { name: "Gabon", code: "+241", iso: "GA", flag: "https://flagcdn.com/w40/ga.png" },
  { name: "Gambia", code: "+220", iso: "GM", flag: "https://flagcdn.com/w40/gm.png" },
  { name: "Georgia", code: "+995", iso: "GE", flag: "https://flagcdn.com/w40/ge.png" },
  { name: "Germany", code: "+49", iso: "DE", flag: "https://flagcdn.com/w40/de.png" },
  { name: "Ghana", code: "+233", iso: "GH", flag: "https://flagcdn.com/w40/gh.png" },
  { name: "Gibraltar", code: "+350", iso: "GI", flag: "https://flagcdn.com/w40/gi.png" },
  { name: "Greece", code: "+30", iso: "GR", flag: "https://flagcdn.com/w40/gr.png" },
  { name: "Greenland", code: "+299", iso: "GL", flag: "https://flagcdn.com/w40/gl.png" },
  { name: "Grenada", code: "+1", iso: "GD", flag: "https://flagcdn.com/w40/gd.png" },
  { name: "Guadeloupe", code: "+590", iso: "GP", flag: "https://flagcdn.com/w40/gp.png" },
  { name: "Guam", code: "+1", iso: "GU", flag: "https://flagcdn.com/w40/gu.png" },
  { name: "Guatemala", code: "+502", iso: "GT", flag: "https://flagcdn.com/w40/gt.png" },
  { name: "Guinea", code: "+224", iso: "GN", flag: "https://flagcdn.com/w40/gn.png" },
  { name: "Guinea-Bissau", code: "+245", iso: "GW", flag: "https://flagcdn.com/w40/gw.png" },
  { name: "Guyana", code: "+592", iso: "GY", flag: "https://flagcdn.com/w40/gy.png" },
  { name: "Haiti", code: "+509", iso: "HT", flag: "https://flagcdn.com/w40/ht.png" },
  { name: "Honduras", code: "+504", iso: "HN", flag: "https://flagcdn.com/w40/hn.png" },
  { name: "Hong Kong", code: "+852", iso: "HK", flag: "https://flagcdn.com/w40/hk.png" },
  { name: "Hungary", code: "+36", iso: "HU", flag: "https://flagcdn.com/w40/hu.png" },
  { name: "Iceland", code: "+354", iso: "IS", flag: "https://flagcdn.com/w40/is.png" },
  { name: "India", code: "+91", iso: "IN", flag: "https://flagcdn.com/w40/in.png" },
  { name: "Iran", code: "+98", iso: "IR", flag: "https://flagcdn.com/w40/ir.png" },
  { name: "Iraq", code: "+964", iso: "IQ", flag: "https://flagcdn.com/w40/iq.png" },
  { name: "Ireland", code: "+353", iso: "IE", flag: "https://flagcdn.com/w40/ie.png" },
  { name: "Israel", code: "+972", iso: "IL", flag: "https://flagcdn.com/w40/il.png" },
  { name: "Italy", code: "+39", iso: "IT", flag: "https://flagcdn.com/w40/it.png" },
  { name: "Ivory Coast", code: "+225", iso: "CI", flag: "https://flagcdn.com/w40/ci.png" },
  { name: "Jamaica", code: "+1", iso: "JM", flag: "https://flagcdn.com/w40/jm.png" },
  { name: "Japan", code: "+81", iso: "JP", flag: "https://flagcdn.com/w40/jp.png" },
  { name: "Jordan", code: "+962", iso: "JO", flag: "https://flagcdn.com/w40/jo.png" },
  { name: "Kazakhstan", code: "+7", iso: "KZ", flag: "https://flagcdn.com/w40/kz.png" },
  { name: "Kenya", code: "+254", iso: "KE", flag: "https://flagcdn.com/w40/ke.png" },
  { name: "Kiribati", code: "+686", iso: "KI", flag: "https://flagcdn.com/w40/ki.png" },
  { name: "Kosovo", code: "+383", iso: "XK", flag: "https://flagcdn.com/w40/xk.png" },
  { name: "Kuwait", code: "+965", iso: "KW", flag: "https://flagcdn.com/w40/kw.png" },
  { name: "Kyrgyzstan", code: "+996", iso: "KG", flag: "https://flagcdn.com/w40/kg.png" },
  { name: "Laos", code: "+856", iso: "LA", flag: "https://flagcdn.com/w40/la.png" },
  { name: "Latvia", code: "+371", iso: "LV", flag: "https://flagcdn.com/w40/lv.png" },
  { name: "Lebanon", code: "+961", iso: "LB", flag: "https://flagcdn.com/w40/lb.png" },
  { name: "Lesotho", code: "+266", iso: "LS", flag: "https://flagcdn.com/w40/ls.png" },
  { name: "Liberia", code: "+231", iso: "LR", flag: "https://flagcdn.com/w40/lr.png" },
  { name: "Libya", code: "+218", iso: "LY", flag: "https://flagcdn.com/w40/ly.png" },
  { name: "Liechtenstein", code: "+423", iso: "LI", flag: "https://flagcdn.com/w40/li.png" },
  { name: "Lithuania", code: "+370", iso: "LT", flag: "https://flagcdn.com/w40/lt.png" },
  { name: "Luxembourg", code: "+352", iso: "LU", flag: "https://flagcdn.com/w40/lu.png" },
  { name: "Macao", code: "+853", iso: "MO", flag: "https://flagcdn.com/w40/mo.png" },
  { name: "Macedonia", code: "+389", iso: "MK", flag: "https://flagcdn.com/w40/mk.png" },
  { name: "Madagascar", code: "+261", iso: "MG", flag: "https://flagcdn.com/w40/mg.png" },
  { name: "Malawi", code: "+265", iso: "MW", flag: "https://flagcdn.com/w40/mw.png" },
  { name: "Maldives", code: "+960", iso: "MV", flag: "https://flagcdn.com/w40/mv.png" },
  { name: "Mali", code: "+223", iso: "ML", flag: "https://flagcdn.com/w40/ml.png" },
  { name: "Malta", code: "+356", iso: "MT", flag: "https://flagcdn.com/w40/mt.png" },
  { name: "Marshall Islands", code: "+692", iso: "MH", flag: "https://flagcdn.com/w40/mh.png" },
  { name: "Martinique", code: "+596", iso: "MQ", flag: "https://flagcdn.com/w40/mq.png" },
  { name: "Mauritania", code: "+222", iso: "MR", flag: "https://flagcdn.com/w40/mr.png" },
  { name: "Mauritius", code: "+230", iso: "MU", flag: "https://flagcdn.com/w40/mu.png" },
  { name: "Mayotte", code: "+262", iso: "YT", flag: "https://flagcdn.com/w40/yt.png" },
  { name: "Mexico", code: "+52", iso: "MX", flag: "https://flagcdn.com/w40/mx.png" },
  { name: "Micronesia", code: "+691", iso: "FM", flag: "https://flagcdn.com/w40/fm.png" },
  { name: "Moldova", code: "+373", iso: "MD", flag: "https://flagcdn.com/w40/md.png" },
  { name: "Monaco", code: "+377", iso: "MC", flag: "https://flagcdn.com/w40/mc.png" },
  { name: "Mongolia", code: "+976", iso: "MN", flag: "https://flagcdn.com/w40/mn.png" },
  { name: "Montenegro", code: "+382", iso: "ME", flag: "https://flagcdn.com/w40/me.png" },
  { name: "Montserrat", code: "+1", iso: "MS", flag: "https://flagcdn.com/w40/ms.png" },
  { name: "Morocco", code: "+212", iso: "MA", flag: "https://flagcdn.com/w40/ma.png" },
  { name: "Mozambique", code: "+258", iso: "MZ", flag: "https://flagcdn.com/w40/mz.png" },
  { name: "Myanmar", code: "+95", iso: "MM", flag: "https://flagcdn.com/w40/mm.png" },
  { name: "Namibia", code: "+264", iso: "NA", flag: "https://flagcdn.com/w40/na.png" },
  { name: "Nauru", code: "+674", iso: "NR", flag: "https://flagcdn.com/w40/nr.png" },
  { name: "Nepal", code: "+977", iso: "NP", flag: "https://flagcdn.com/w40/np.png" },
  { name: "Netherlands", code: "+31", iso: "NL", flag: "https://flagcdn.com/w40/nl.png" },
  { name: "Netherlands Antilles", code: "+599", iso: "AN", flag: "https://flagcdn.com/w40/an.png" },
  { name: "New Caledonia", code: "+687", iso: "NC", flag: "https://flagcdn.com/w40/nc.png" },
  { name: "New Zealand", code: "+64", iso: "NZ", flag: "https://flagcdn.com/w40/nz.png" },
  { name: "Nicaragua", code: "+505", iso: "NI", flag: "https://flagcdn.com/w40/ni.png" },
  { name: "Niger", code: "+227", iso: "NE", flag: "https://flagcdn.com/w40/ne.png" },
  { name: "Nigeria", code: "+234", iso: "NG", flag: "https://flagcdn.com/w40/ng.png" },
  { name: "Niue", code: "+683", iso: "NU", flag: "https://flagcdn.com/w40/nu.png" },
  { name: "Northern Mariana Islands", code: "+1", iso: "MP", flag: "https://flagcdn.com/w40/mp.png" },
  { name: "North Korea", code: "+850", iso: "KP", flag: "https://flagcdn.com/w40/kp.png" },
  { name: "Norway", code: "+47", iso: "NO", flag: "https://flagcdn.com/w40/no.png" },
  { name: "Oman", code: "+968", iso: "OM", flag: "https://flagcdn.com/w40/om.png" },
  { name: "Pakistan", code: "+92", iso: "PK", flag: "https://flagcdn.com/w40/pk.png" },
  { name: "Palau", code: "+680", iso: "PW", flag: "https://flagcdn.com/w40/pw.png" },
  { name: "Palestine", code: "+970", iso: "PS", flag: "https://flagcdn.com/w40/ps.png" },
  { name: "Panama", code: "+507", iso: "PA", flag: "https://flagcdn.com/w40/pa.png" },
  { name: "Papua New Guinea", code: "+675", iso: "PG", flag: "https://flagcdn.com/w40/pg.png" },
  { name: "Paraguay", code: "+595", iso: "PY", flag: "https://flagcdn.com/w40/py.png" },
  { name: "Peru", code: "+51", iso: "PE", flag: "https://flagcdn.com/w40/pe.png" },
  { name: "Poland", code: "+48", iso: "PL", flag: "https://flagcdn.com/w40/pl.png" },
  { name: "Portugal", code: "+351", iso: "PT", flag: "https://flagcdn.com/w40/pt.png" },
  { name: "Puerto Rico", code: "+1", iso: "PR", flag: "https://flagcdn.com/w40/pr.png" },
  { name: "Qatar", code: "+974", iso: "QA", flag: "https://flagcdn.com/w40/qa.png" },
  { name: "Reunion", code: "+262", iso: "RE", flag: "https://flagcdn.com/w40/re.png" },
  { name: "Romania", code: "+40", iso: "RO", flag: "https://flagcdn.com/w40/ro.png" },
  { name: "Russia", code: "+7", iso: "RU", flag: "https://flagcdn.com/w40/ru.png" },
  { name: "Rwanda", code: "+250", iso: "RW", flag: "https://flagcdn.com/w40/rw.png" },
  { name: "Saint Kitts and Nevis", code: "+1", iso: "KN", flag: "https://flagcdn.com/w40/kn.png" },
  { name: "Saint Lucia", code: "+1", iso: "LC", flag: "https://flagcdn.com/w40/lc.png" },
  { name: "Saint Vincent and the Grenadines", code: "+1", iso: "VC", flag: "https://flagcdn.com/w40/vc.png" },
  { name: "Samoa", code: "+685", iso: "WS", flag: "https://flagcdn.com/w40/ws.png" },
  { name: "San Marino", code: "+378", iso: "SM", flag: "https://flagcdn.com/w40/sm.png" },
  { name: "Sao Tome and Principe", code: "+239", iso: "ST", flag: "https://flagcdn.com/w40/st.png" },
  { name: "Saudi Arabia", code: "+966", iso: "SA", flag: "https://flagcdn.com/w40/sa.png" },
  { name: "Senegal", code: "+221", iso: "SN", flag: "https://flagcdn.com/w40/sn.png" },
  { name: "Serbia", code: "+381", iso: "RS", flag: "https://flagcdn.com/w40/rs.png" },
  { name: "Seychelles", code: "+248", iso: "SC", flag: "https://flagcdn.com/w40/sc.png" },
  { name: "Sierra Leone", code: "+232", iso: "SL", flag: "https://flagcdn.com/w40/sl.png" },
  { name: "Slovakia", code: "+421", iso: "SK", flag: "https://flagcdn.com/w40/sk.png" },
  { name: "Slovenia", code: "+386", iso: "SI", flag: "https://flagcdn.com/w40/si.png" },
  { name: "Solomon Islands", code: "+677", iso: "SB", flag: "https://flagcdn.com/w40/sb.png" },
  { name: "Somalia", code: "+252", iso: "SO", flag: "https://flagcdn.com/w40/so.png" },
  { name: "South Africa", code: "+27", iso: "ZA", flag: "https://flagcdn.com/w40/za.png" },
  { name: "South Korea", code: "+82", iso: "KR", flag: "https://flagcdn.com/w40/kr.png" },
  { name: "South Sudan", code: "+211", iso: "SS", flag: "https://flagcdn.com/w40/ss.png" },
  { name: "Spain", code: "+34", iso: "ES", flag: "https://flagcdn.com/w40/es.png" },
  { name: "Sri Lanka", code: "+94", iso: "LK", flag: "https://flagcdn.com/w40/lk.png" },
  { name: "Sudan", code: "+249", iso: "SD", flag: "https://flagcdn.com/w40/sd.png" },
  { name: "Suriname", code: "+597", iso: "SR", flag: "https://flagcdn.com/w40/sr.png" },
  { name: "Swaziland", code: "+268", iso: "SZ", flag: "https://flagcdn.com/w40/sz.png" },
  { name: "Sweden", code: "+46", iso: "SE", flag: "https://flagcdn.com/w40/se.png" },
  { name: "Switzerland", code: "+41", iso: "CH", flag: "https://flagcdn.com/w40/ch.png" },
  { name: "Syria", code: "+963", iso: "SY", flag: "https://flagcdn.com/w40/sy.png" },
  { name: "Taiwan", code: "+886", iso: "TW", flag: "https://flagcdn.com/w40/tw.png" },
  { name: "Tajikistan", code: "+992", iso: "TJ", flag: "https://flagcdn.com/w40/tj.png" },
  { name: "Tanzania", code: "+255", iso: "TZ", flag: "https://flagcdn.com/w40/tz.png" },
  { name: "Togo", code: "+228", iso: "TG", flag: "https://flagcdn.com/w40/tg.png" },
  { name: "Tokelau", code: "+690", iso: "TK", flag: "https://flagcdn.com/w40/tk.png" },
  { name: "Tonga", code: "+676", iso: "TO", flag: "https://flagcdn.com/w40/to.png" },
  { name: "Trinidad and Tobago", code: "+1", iso: "TT", flag: "https://flagcdn.com/w40/tt.png" },
  { name: "Tunisia", code: "+216", iso: "TN", flag: "https://flagcdn.com/w40/tn.png" },
  { name: "Turkey", code: "+90", iso: "TR", flag: "https://flagcdn.com/w40/tr.png" },
  { name: "Turkmenistan", code: "+993", iso: "TM", flag: "https://flagcdn.com/w40/tm.png" },
  { name: "Turks and Caicos Islands", code: "+1", iso: "TC", flag: "https://flagcdn.com/w40/tc.png" },
  { name: "Tuvalu", code: "+688", iso: "TV", flag: "https://flagcdn.com/w40/tv.png" },
  { name: "Uganda", code: "+256", iso: "UG", flag: "https://flagcdn.com/w40/ug.png" },
  { name: "Ukraine", code: "+380", iso: "UA", flag: "https://flagcdn.com/w40/ua.png" },
  { name: "United Arab Emirates", code: "+971", iso: "AE", flag: "https://flagcdn.com/w40/ae.png" },
  { name: "United Kingdom", code: "+44", iso: "GB", flag: "https://flagcdn.com/w40/gb.png" },
  { name: "United States", code: "+1", iso: "US", flag: "https://flagcdn.com/w40/us.png" },
  { name: "Uruguay", code: "+598", iso: "UY", flag: "https://flagcdn.com/w40/uy.png" },
  { name: "Uzbekistan", code: "+998", iso: "UZ", flag: "https://flagcdn.com/w40/uz.png" },
  { name: "Vanuatu", code: "+678", iso: "VU", flag: "https://flagcdn.com/w40/vu.png" },
  { name: "Venezuela", code: "+58", iso: "VE", flag: "https://flagcdn.com/w40/ve.png" },
  { name: "Virgin Islands, British", code: "+1", iso: "VG", flag: "https://flagcdn.com/w40/vg.png" },
  { name: "Virgin Islands, U.S.", code: "+1", iso: "VI", flag: "https://flagcdn.com/w40/vi.png" },
  { name: "Wallis and Futuna", code: "+681", iso: "WF", flag: "https://flagcdn.com/w40/wf.png" },
  { name: "Yemen", code: "+967", iso: "YE", flag: "https://flagcdn.com/w40/ye.png" },
  { name: "Zambia", code: "+260", iso: "ZM", flag: "https://flagcdn.com/w40/zm.png" },
  { name: "Zimbabwe", code: "+263", iso: "ZW", flag: "https://flagcdn.com/w40/zw.png" },
];
